version: '2'
services:
  app:
    extends:
      file: docker/docker-compose.common.yml
      service: app
    volumes: # TODO pull dependencies out of project folder: https://github.com/ember-cli/ember-cli/pull/3698
      - ./app/:/usr/src/app/app/
      - ./config/:/usr/src/app/config/
      - ./package.json:/usr/src/app/package.json
      - ./bower.json:/usr/src/app/bower.json
      - ./ember-cli-build.js:/usr/src/app/ember-cli-build.js
      - ./scripts/:/usr/src/app/scripts/
      - ./tests/:/usr/src/app/tests/
      - ./vendor/:/usr/src/app/vendor/
      - ./dist/:/usr/src/app/dist/
    ports:
      - 4200:4200
      - 49152:49152

  server:
    extends:
      file: docker/docker-compose.common.yml
      service: server
    ports:
      - 8000:8000
    links:
      - server_db:db

  server_db:
    extends:
      file: docker/docker-compose.common.yml
      service: server_db

