version: '2'
services:
  app:
    build: ..
    ports:
      - 4200
      - 49152
    command:
      - scripts/start_server.sh
    env_file:
      - development.env

  server:
    extends:
      file: ../server/docker/docker-compose.common.yml
      service: app

  server_db:
    extends:
      file: ../server/docker/docker-compose.common.yml
      service: db

